In [1]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

In [2]:
# Seting seed
random.seed(42)
np.random.seed(42)

In [3]:
# Customer count
num_customers = 10000

In [4]:
customers = pd.DataFrame({"customer_id": range(1, num_customers + 1), "age": np.random.randint(18, 70, num_customers),"country": np.random.choice(["India", "USA", "UK", "Germany"], num_customers),
                          "account_age_days": np.random.randint(1, 3650, num_customers)})

In [5]:
customers.head()

   customer_id  age  country  account_age_days
0            1   56       UK              3457
1            2   69      USA               988
2            3   46      USA              1222
3            4   32  Germany              2095
4            5   60    India              1764

In [6]:
# Devices and Ips
num_devices = 5000
num_ips = 8000

In [8]:
# device_1, ip_1
devices = [f"device_{i}" for i in range(num_devices)]
ips = [f"ip_{i}" for i in range(num_ips)]

In [9]:
# Transactions
num_transactions = 200000

In [10]:
# Swipe, Internet, cash
transaction_types = ["POS", "Online", "ATM"]

In [11]:
merchant_categories = ["Food", "Electronics", "Travel", "Shopping"]

In [29]:
# Making a table:
transactions = pd.DataFrame({
        "transaction_id": range(1, num_transactions + 1),
        "customer_id": np.random.choice(customers["customer_id"], num_transactions),
        "amount": np.round(np.random.exponential(scale=100, size=num_transactions) + 1,2),
        "transaction_type": np.random.choice(transaction_types, num_transactions),
        "merchant_category": np.random.choice(merchant_categories, num_transactions),
})

In [30]:
# Time stamp
start_date = datetime(2023, 1, 1)
transactions["timestamp"] = [start_date + timedelta(minutes=random.randint(0, 60*24*365))
                            for _ in range(num_transactions)
                            ]

In [31]:
# Merging both tables
data = transactions.merge(customers, on="customer_id", how="left")

In [32]:
# Behaviours
data["device_id"] = np.random.choice(devices, len(data)) #Assign device to each transaction, 
data["ip_id"] = np.random.choice(ips, len(data)) # What device type
data["ip_country"] = np.random.choice(["India", "USA", "UK", "Germany"], len(data)) # Where transaction came from
data["hour"] = data["timestamp"].dt.hour #Extract hour (0–23)
data["transactions_last_hour"] = np.random.randint(1, 10, len(data)) #How many transactions recently

In [33]:
data

,transaction_id,customer_id,amount,transaction_type,merchant_category,timestamp,age,country,account_age_days,device_id,ip_id,ip_country,hour,transactions_last_hour
0,1,8445,65.54,POS,Electronics,2023-09-24 01:23:00,41,USA,2656,device_2056,ip_3474,UK,1,1
1,2,3856,72.56,Online,Travel,2023-04-03 06:30:00,57,India,1073,device_595,ip_4880,India,6,7
2,3,7064,64.55,POS,Shopping,2023-10-06 23:26:00,31,Germany,2217,device_1258,ip_5155,USA,23,1
3,4,5171,246.46,ATM,Food,2023-05-02 02:50:00,62,Germany,2046,device_2089,ip_825,Germany,2,7
4,5,4433,62.39,POS,Electronics,2023-02-13 00:26:00,39,India,2134,device_4470,ip_6074,Germany,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199996,2154,22.15,Online,Food,2023-02-07 11:16:00,47,USA,2830,device_1004,ip_2536,India,11,2
199996,199997,6892,162.12,Online,Food,2023-06-11 18:38:00,18,UK,2312,device_3797,ip_2789,Germany,18,2
199997,199998,1148,184.20,POS,Travel,2023-03-27 01:30:00,25,India,2666,device_4361,ip_4486,India,1,7
199998,199999,2621,115.23,Online,Shopping,2023-01-01 13:24:00,25,USA,1990,device_979,ip_7975,Germany,13,5
199999,200000,2568,338.27,ATM,Food,2023-11-27 03:44:00,56,India,1994,device_2707,ip_2862,Germany,3,7

In [34]:
data.head()

,transaction_id,customer_id,amount,transaction_type,merchant_category,timestamp,age,country,account_age_days,device_id,ip_id,ip_country,hour,transactions_last_hour
0,1,8445,65.54,POS,Electronics,2023-09-24 01:23:00,41,USA,2656,device_2056,ip_3474,UK,1,1
1,2,3856,72.56,Online,Travel,2023-04-03 06:30:00,57,India,1073,device_595,ip_4880,India,6,7
2,3,7064,64.55,POS,Shopping,2023-10-06 23:26:00,31,Germany,2217,device_1258,ip_5155,USA,23,1
3,4,5171,246.46,ATM,Food,2023-05-02 02:50:00,62,Germany,2046,device_2089,ip_825,Germany,2,7
4,5,4433,62.39,POS,Electronics,2023-02-13 00:26:00,39,India,2134,device_4470,ip_6074,Germany,0,4

In [35]:
data.describe(include="all")

,transaction_id,customer_id,amount,transaction_type,merchant_category,timestamp,age,country,account_age_days,device_id,ip_id,ip_country,hour,transactions_last_hour
count,200000.000000,200000.000000,200000.000000,200000,200000,200000,200000.000000,200000,200000.000000,200000,200000,200000,200000.000000,200000.00000
unique,NaN,NaN,NaN,3,4,NaN,NaN,4,NaN,5000,8000,4,NaN,NaN
top,NaN,NaN,NaN,Online,Electronics,NaN,NaN,Germany,NaN,device_1618,ip_3584,USA,NaN,NaN
freq,NaN,NaN,NaN,66897,50657,NaN,NaN,50675,NaN,65,49,50253,NaN,NaN
mean,100000.500000,5002.538605,101.128106,NaN,NaN,2023-07-02 07:27:21.940800256,43.550115,NaN,1829.362485,NaN,NaN,NaN,11.483480,5.00502
min,1.000000,1.000000,1.000000,NaN,NaN,2023-01-01 00:00:00,18.000000,NaN,1.000000,NaN,NaN,NaN,0.000000,1.00000
25%,50000.750000,2511.000000,29.750000,NaN,NaN,2023-04-01 20:25:30,31.000000,NaN,917.000000,NaN,NaN,NaN,5.000000,3.00000
50%,100000.500000,5004.000000,70.300000,NaN,NaN,2023-07-02 11:25:30,43.000000,NaN,1821.000000,NaN,NaN,NaN,11.000000,5.00000
75%,150000.250000,7493.000000,139.930000,NaN,NaN,2023-10-01 13:21:30,56.000000,NaN,2747.000000,NaN,NaN,NaN,17.000000,7.00000
max,200000.000000,10000.000000,1314.430000,NaN,NaN,2023-12-31 23:57:00,69.000000,NaN,3649.000000,NaN,NaN,NaN,23.000000,9.00000
std,57735.171256,2885.646176,100.185384,NaN,NaN,NaN,14.909538,NaN,1054.588864,NaN,NaN,NaN,6.923892,2.58208

In [36]:
# Fraud Ring.
fraud_devices = random.sample(devices, 50)


data["is_fraud_ring"] = data["device_id"].apply(
    lambda x: 1 if x in fraud_devices else 0
)

In [47]:
# Fraud fucntion
def detect_fraud(row):
    score = 0

    if row["amount"] > 1500 and row["account_age_days"] < 60:
        score += 1

    if row["transactions_last_hour"] > 7:
        score += 1

    if row["country"] != row["ip_country"]:
        score += 1

    if row["hour"] < 4:
        score += 1

    if row["is_fraud_ring"] == 1:
        score += 2  # strong signal

    
    if score >= 3:
        fraud = 1
    elif score == 2 and random.random() < 0.5:
        fraud = 1
    else:
        fraud = 0

    return fraud

In [48]:
# Fraud Label
data["fraud"] = data.apply(detect_fraud, axis=1)

#Distribution
data["fraud"].value_counts(normalize=True)

fraud
0    0.84144
1    0.15856
Name: proportion, dtype: float64

In [49]:
#Edge List
edges = []

# Customer → Transaction
edges += list(zip(
    "cust_" + data["customer_id"].astype(str),
    "txn_" + data["transaction_id"].astype(str)
))

# Transaction → Device
edges += list(zip(
    "txn_" + data["transaction_id"].astype(str),
    data["device_id"]
))

# Transaction → IP
edges += list(zip(
    "txn_" + data["transaction_id"].astype(str),
    data["ip_id"]
))

In [50]:
edges_df = pd.DataFrame(edges, columns=["source", "target"])

edges_df.head()

      source target
0  cust_8445  txn_1
1  cust_3856  txn_2
2  cust_7064  txn_3
3  cust_5171  txn_4
4  cust_4433  txn_5

In [51]:
data.to_csv("gnn_fraud_dataset.csv", index=False)
edges_df.to_csv("gnn_edges.csv", index=False)

In [52]:
print("Fraud Ratio:")
print(data["fraud"].value_counts(normalize=True))

print("\nTotal Edges:", len(edges_df))

Fraud Ratio:
fraud
0    0.84144
1    0.15856
Name: proportion, dtype: float64

Total Edges: 600000